### ISSUE TITLE
Failure to download updates possibly causing Steam reprompting for password

### ISSUE THREAD

**Issue by barryjj** [PhantomGamers/SteamFriendsPatcher#18]
I came back to my PC and noticed steam was doing the password prompt thing -- exited and had to restart the client and provide both 2FA code and password.  I've seen this situation a few times recently and thought maybe I was having some sort of connection issues with Steam/Valve but then I talked to a friend who was also using friends patcher (both of us were using it to keep changes to the CSS library files active for theme customization) and he mentioned he had a bunch of problems with the Friends list blanking out and having to restart the client to fix... he ended up being annoyed enough to clean out the theming and do a fresh install of his Steam client and hasn't had the problem since.  This is the first time I'd seen a logout/password prompt situation on my client since, so I checked steam friends patcher and noticed in the last 45m or so that it had problems downloading a file.  This combined with the friends list being open (I almost never have it open outside of the overlay) and displaying the reconnect/offline text is making me wonder if being unable to download when an update is available might be the root cause of the behaviour seen by me and my friend.

Trace:
2/6/2021 8:57:05 PM] [Error] Failed to download friends.css from https://steamcommunity-a.akamaihd.net/public/css/webui/friends.css.
[2/6/2021 8:57:05 PM] [Error] System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SteamFriendsPatcher.Program.GetLatestFriendsCss(Boolean force) in C:\Users\Phantom\source\repos\SteamFriendsPatcher\Program.cs:line 412

**Comment by PhantomGamers** [comment]
I'll keep this open for now in case maybe some developments are made on this issue but to me it seems more likely that the issue is that Steam is invalidating your login after having these connection problems... if the patcher fails to download the friends.css, this would only mean that the patcher would be unable to find a friends.css to patch, meaning it would do nothing (and not somehow cause Steam to log you out)

Even if you use the clear cache button in the patcher, it does not remove any files that would cause Steam to log you out. I can't see anything the patcher does causing such an issue.

**Comment by xamionex** [comment]
Bump, had the same issue though I turned off the patcher and let it download, after doing so it started up successfully but now every time I restart it asks for my password, even if the patcher is off? I'll do some digging and see if I can figure it out
